dist: trusty

language: bash

env:
  global:
    - PASS_VERSION=1.7.1

addons:
  apt:
    packages:
      - tree
      - xclip
      - shellcheck
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

before_script:
  - apt-get install gpg2
  - ln -s /usr/bin/gpg2 /usr/local/bin/gpg
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
  - echo "deb https://dl.bintray.com/jamesridgway/debian xenial main" | sudo tee -a /etc/apt/sources.list
  - apt-get update
  - apt-get install bsearch
  - export PREFIX=$HOME/.bin/usr PATH="$PATH:$HOME/.bin/usr/bin"
  - wget https://git.zx2c4.com/password-store/snapshot/password-store-$PASS_VERSION.tar.xz
  - tar -xf password-store-$PASS_VERSION.tar.xz
  - make --directory=password-store-$PASS_VERSION install

script:
  - make lint
  - make test